Dado = input('Digite uma algo: ')
print('O tipo primitivo é ', type(Dado))
print('Só tem espaço? ', Dado.isspace())
print('É um numero? ', Dado.isnumeric())
print('é alfabetico? ', Dado.isalpha())
print('é alfanumerico? ', Dado.isalnum())
print('Está em maiuscula? ', Dado.isupper())
print('Está em minuscula? ', Dado.islower())
print('Está capitalizada? ', Dado.istitle)